---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  labels:
    demo: pvc-demo
spec:
  volumes:
  - name: vol-01
    persistentVolumeClaim:
      claimName: demo-vol-01
  containers:
  - name: centos-container
    image: ghcr.io/gowatana/centos7:httpd
    ports:
    - containerPort: 80
    volumeMounts:
    - name: vol-01
      mountPath: "/mnt/data"
