# ベースイメージ
FROM nvcr.io/nvidia/tensorflow:23.03-tf2-py3

# 依存関係のインストール
#RUN pip install tensorflow numpy

# スクリプトを追加
COPY train_and_save_model.py /train_and_save_model.py

# 実行コマンド
#ENTRYPOINT ["python", "/train_and_save_model.py"]

