# ベースイメージ
FROM nvcr.io/nvidia/tensorflow:23.03-tf2-py3

# 依存関係のインストール
#RUN pip install tensorflow numpy

# スクリプトを追加
COPY predict_model.py /predict_model.py

# 実行コマンド
#ENTRYPOINT ["python", "/predict_model.py"]

